services:
  - type: web
    name: wasel-amin
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        value: wasel_secret_key_1994_secure
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_PATH
        value: /app/data/app.db
      - key: UPLOAD_PATH
        value: /app/uploads
      - key: SESSION_PATH
        value: /app/src/auth_sessions
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: SUPPRESS_NO_CONFIG_WARNING
        value: true
